// GENERATED by `node scripts/sync-idl.mjs` from target/idl/propamm_vault.json.
// Do not edit by hand: the next sync overwrites it. The source of truth is the Rust program.
//
// Field names here are in snake_case — the way Anchor writes them. The crossing to
// camelCase happens in exactly one place, the layout tables in `src/codecs.ts`.

import type { PropammVaultIdl } from './idl-schema.js'

export const PROPAMM_VAULT_IDL: PropammVaultIdl = {
  "address": "77Y9n3vWE2noN1u9PTshuWxdDRsrw9UMtejBypUD9wjq",
  "metadata": {
    "name": "propamm_vault",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "PropAMM on-chain program: a vault for one pair with the quote inside the account",
    "repository": "https://github.com/PropAMMForge/PropAMM-Forge"
  },
  "instructions": [
    {
      "name": "clear_quote",
      "docs": [
        "Clear the quote (FR-014) — the feed went silent, and repeating the last",
        "known price is worse than not quoting at all."
      ],
      "discriminator": [
        115,
        201,
        171,
        238,
        207,
        192,
        17,
        97
      ],
      "accounts": [
        {
          "name": "pricing_authority",
          "docs": [
            "The quote signer (FR-010). The owner of the capital is not needed here — and",
            "that is the whole point of separating the authorities."
          ],
          "signer": true,
          "relations": [
            "vault"
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "vault.owner",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.base_mint",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.quote_mint",
                "account": "Vault"
              }
            ]
          }
        }
      ],
      "args": []
    },
    {
      "name": "deposit",
      "docs": [
        "Treasury deposit by the owner (FR-003)."
      ],
      "discriminator": [
        242,
        35,
        198,
        137,
        82,
        225,
        242,
        182
      ],
      "accounts": [
        {
          "name": "owner",
          "docs": [
            "The only one who may move capital (FR-002, FR-003)."
          ],
          "signer": true,
          "relations": [
            "vault"
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "account",
                "path": "vault.base_mint",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.quote_mint",
                "account": "Vault"
              }
            ]
          }
        },
        {
          "name": "mint",
          "docs": [
            "Mint of the side being moved; it is what determines the side."
          ]
        },
        {
          "name": "treasury",
          "docs": [
            "Treasury of that side — checked against the vault state in the handler."
          ],
          "writable": true
        },
        {
          "name": "owner_token_account",
          "docs": [
            "The owner's account: source on `deposit`, recipient on `withdraw`."
          ],
          "writable": true
        },
        {
          "name": "token_program"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "initialize_vault",
      "docs": [
        "Deployment: the pair is fixed forever, the treasury is created empty,",
        "there is no quote yet (FR-001, FR-002, FR-004, FR-005)."
      ],
      "discriminator": [
        48,
        191,
        163,
        44,
        71,
        129,
        63,
        164
      ],
      "accounts": [
        {
          "name": "owner",
          "docs": [
            "Owner of the capital and payer for the created accounts (FR-002)."
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "base_mint",
          "docs": [
            "Base asset of the pair.",
            "",
            "The mint account's `owner` is checked against the token program passed in",
            "explicitly: the pair may mix classic SPL and Token-2022, and without this check",
            "a side would go to the wrong program with an obscure error inside the CPI."
          ]
        },
        {
          "name": "quote_mint",
          "docs": [
            "Quote asset of the pair."
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "account",
                "path": "base_mint"
              },
              {
                "kind": "account",
                "path": "quote_mint"
              }
            ]
          }
        },
        {
          "name": "base_vault",
          "docs": [
            "Treasury of the base asset — an ATA owned by the PDA.",
            "",
            "`init_if_needed`, not `init`, and that is not a relaxation: an ATA for someone",
            "else's owner can be created by anyone, so with `init` a stranger could block",
            "the deployment forever by creating the account in advance. The ATA address",
            "derives from `(vault, mint, token_program)`, so an \"already created\" account",
            "at that address can have neither a different mint nor a different owner —",
            "there is nothing to substitute here."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "account",
                "path": "vault"
              },
              {
                "kind": "account",
                "path": "base_token_program"
              },
              {
                "kind": "account",
                "path": "base_mint"
              }
            ],
            "program": {
              "kind": "const",
              "value": [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89
              ]
            }
          }
        },
        {
          "name": "quote_vault",
          "docs": [
            "Treasury of the quote asset — an ATA owned by the PDA."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "account",
                "path": "vault"
              },
              {
                "kind": "account",
                "path": "quote_token_program"
              },
              {
                "kind": "account",
                "path": "quote_mint"
              }
            ],
            "program": {
              "kind": "const",
              "value": [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89
              ]
            }
          }
        },
        {
          "name": "base_token_program",
          "docs": [
            "Token program of the base side: classic SPL or Token-2022."
          ]
        },
        {
          "name": "quote_token_program",
          "docs": [
            "Token program of the quote side; may differ from the base one."
          ]
        },
        {
          "name": "associated_token_program",
          "address": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "args",
          "type": {
            "defined": {
              "name": "InitializeVaultArgs"
            }
          }
        }
      ]
    },
    {
      "name": "set_halt_authority",
      "docs": [
        "Replace the emergency-halt signer (FR-024, FR-023c)."
      ],
      "discriminator": [
        242,
        210,
        191,
        241,
        84,
        236,
        173,
        6
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true,
          "relations": [
            "vault"
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "account",
                "path": "vault.base_mint",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.quote_mint",
                "account": "Vault"
              }
            ]
          }
        }
      ],
      "args": [
        {
          "name": "new_authority",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "set_pricing_authority",
      "docs": [
        "Replace the quote signer (FR-010). Clears the current quote:",
        "replacement means the previous price source is no longer trusted."
      ],
      "discriminator": [
        251,
        150,
        119,
        61,
        186,
        221,
        116,
        157
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true,
          "relations": [
            "vault"
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "account",
                "path": "vault.base_mint",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.quote_mint",
                "account": "Vault"
              }
            ]
          }
        }
      ],
      "args": [
        {
          "name": "new_authority",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "set_risk_limits",
      "docs": [
        "Change the risk limits (FR-007, FR-008, FR-026)."
      ],
      "discriminator": [
        97,
        64,
        111,
        145,
        50,
        132,
        147,
        235
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true,
          "relations": [
            "vault"
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "account",
                "path": "vault.base_mint",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.quote_mint",
                "account": "Vault"
              }
            ]
          }
        }
      ],
      "args": [
        {
          "name": "limits",
          "type": {
            "defined": {
              "name": "RiskLimits"
            }
          }
        }
      ]
    },
    {
      "name": "swap",
      "docs": [
        "Swap at the posted quote (FR-007, FR-008, FR-009, FR-026).",
        "Four guards are computed by `propamm_quote`; the program adds `halted`",
        "and the check of the accounts against the state."
      ],
      "discriminator": [
        248,
        198,
        158,
        145,
        225,
        117,
        135,
        200
      ],
      "accounts": [
        {
          "name": "trader",
          "docs": [
            "The one who swaps. They need not be the owner of the capital — this is the",
            "external order flow."
          ],
          "signer": true
        },
        {
          "name": "vault",
          "docs": [
            "Vault state. **Not `mut`:** a swap changes no field — inventory lives in the",
            "token accounts, and the quote stays in force until the next update."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "vault.owner",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.base_mint",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.quote_mint",
                "account": "Vault"
              }
            ]
          }
        },
        {
          "name": "base_treasury",
          "writable": true
        },
        {
          "name": "quote_treasury",
          "writable": true
        },
        {
          "name": "trader_base_account",
          "writable": true
        },
        {
          "name": "trader_quote_account",
          "writable": true
        },
        {
          "name": "base_mint"
        },
        {
          "name": "quote_mint"
        },
        {
          "name": "base_token_program",
          "docs": [
            "Token program of the base side."
          ]
        },
        {
          "name": "quote_token_program",
          "docs": [
            "Token program of the quote side; the pair may be mixed."
          ]
        }
      ],
      "args": [
        {
          "name": "args",
          "type": {
            "defined": {
              "name": "SwapArgs"
            }
          }
        }
      ]
    },
    {
      "name": "update_quote",
      "docs": [
        "Post a quote (FR-006, FR-007). Signed by `pricing_authority`;",
        "`quote_slot` is taken from the chain, not from the arguments."
      ],
      "discriminator": [
        235,
        69,
        162,
        233,
        147,
        53,
        42,
        225
      ],
      "accounts": [
        {
          "name": "pricing_authority",
          "docs": [
            "The quote signer (FR-010). The owner of the capital is not needed here — and",
            "that is the whole point of separating the authorities."
          ],
          "signer": true,
          "relations": [
            "vault"
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "vault.owner",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.base_mint",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.quote_mint",
                "account": "Vault"
              }
            ]
          }
        }
      ],
      "args": [
        {
          "name": "quote",
          "type": {
            "defined": {
              "name": "QuoteUpdate"
            }
          }
        }
      ]
    },
    {
      "name": "withdraw",
      "docs": [
        "Capital withdrawal by the owner (FR-003). Clears the current quote —",
        "client decision of 2026-08-27, rationale in the header of `treasury.rs`."
      ],
      "discriminator": [
        183,
        18,
        70,
        156,
        148,
        109,
        161,
        34
      ],
      "accounts": [
        {
          "name": "owner",
          "docs": [
            "The only one who may move capital (FR-002, FR-003)."
          ],
          "signer": true,
          "relations": [
            "vault"
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "account",
                "path": "vault.base_mint",
                "account": "Vault"
              },
              {
                "kind": "account",
                "path": "vault.quote_mint",
                "account": "Vault"
              }
            ]
          }
        },
        {
          "name": "mint",
          "docs": [
            "Mint of the side being moved; it is what determines the side."
          ]
        },
        {
          "name": "treasury",
          "docs": [
            "Treasury of that side — checked against the vault state in the handler."
          ],
          "writable": true
        },
        {
          "name": "owner_token_account",
          "docs": [
            "The owner's account: source on `deposit`, recipient on `withdraw`."
          ],
          "writable": true
        },
        {
          "name": "token_program"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "Vault",
      "discriminator": [
        211,
        8,
        232,
        43,
        2,
        152,
        117,
        119
      ]
    }
  ],
  "events": [
    {
      "name": "CapitalMoved",
      "discriminator": [
        248,
        32,
        119,
        45,
        64,
        246,
        123,
        194
      ]
    },
    {
      "name": "QuoteCleared",
      "discriminator": [
        120,
        234,
        175,
        196,
        185,
        60,
        223,
        112
      ]
    },
    {
      "name": "QuoteUpdated",
      "discriminator": [
        18,
        34,
        232,
        231,
        132,
        245,
        74,
        136
      ]
    },
    {
      "name": "Swapped",
      "discriminator": [
        217,
        52,
        52,
        83,
        147,
        135,
        96,
        109
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "IdenticalMints",
      "msg": "base and quote mints must differ"
    },
    {
      "code": 6001,
      "name": "MintProgramMismatch",
      "msg": "mint is not owned by the token program passed for its side"
    },
    {
      "code": 6002,
      "name": "InvalidAuthority",
      "msg": "authority cannot be the default pubkey"
    },
    {
      "code": 6003,
      "name": "InvalidRiskLimits",
      "msg": "risk limits are outside their domain"
    },
    {
      "code": 6004,
      "name": "OwnerOnly",
      "msg": "only the vault owner may move capital"
    },
    {
      "code": 6005,
      "name": "PricingAuthorityOnly",
      "msg": "only the pricing authority may quote"
    },
    {
      "code": 6006,
      "name": "InvalidQuote",
      "msg": "quote parameters are outside the domain the math accepts"
    },
    {
      "code": 6007,
      "name": "VaultHalted",
      "msg": "vault is halted"
    },
    {
      "code": 6008,
      "name": "UnknownMint",
      "msg": "mint is not part of this vault's pair"
    },
    {
      "code": 6009,
      "name": "TreasuryAccountMismatch",
      "msg": "treasury account does not belong to this vault side"
    },
    {
      "code": 6010,
      "name": "ZeroAmount",
      "msg": "amount must be greater than zero"
    },
    {
      "code": 6011,
      "name": "InsufficientVaultBalance",
      "msg": "vault does not hold that much of the asset"
    },
    {
      "code": 6012,
      "name": "QuoteNotSet",
      "msg": "quote is not set"
    },
    {
      "code": 6013,
      "name": "QuoteStale",
      "msg": "quote is older than the freshness limit"
    },
    {
      "code": 6014,
      "name": "SizeExceeded",
      "msg": "base leg exceeds the maximum quoted size"
    },
    {
      "code": 6015,
      "name": "SlippageExceeded",
      "msg": "result is worse than the declared limit"
    },
    {
      "code": 6016,
      "name": "InventoryBound",
      "msg": "swap would push inventory past the hard bound"
    },
    {
      "code": 6017,
      "name": "InsufficientLiquidity",
      "msg": "vault cannot pay out that amount"
    },
    {
      "code": 6018,
      "name": "AmountTooSmall",
      "msg": "amount rounds to zero"
    },
    {
      "code": 6019,
      "name": "MathOverflow",
      "msg": "intermediate value overflowed"
    },
    {
      "code": 6020,
      "name": "AccountMismatch",
      "msg": "account does not match the one recorded in the vault"
    },
    {
      "code": 6021,
      "name": "MintHasTransferFee",
      "msg": "mint has a transfer fee: received amount would differ from sent"
    },
    {
      "code": 6022,
      "name": "MintHasTransferHook",
      "msg": "mint has a transfer hook: transfer behaviour is not ours to predict"
    },
    {
      "code": 6023,
      "name": "MintHasPermanentDelegate",
      "msg": "mint has a permanent delegate: vault funds could be moved without us"
    },
    {
      "code": 6024,
      "name": "MintIsNonTransferable",
      "msg": "mint is non-transferable"
    },
    {
      "code": 6025,
      "name": "MintDefaultsToFrozen",
      "msg": "mint freezes new accounts by default"
    },
    {
      "code": 6026,
      "name": "MintIsPausable",
      "msg": "mint is pausable: transfers can be stopped by a third party"
    },
    {
      "code": 6027,
      "name": "MintExtensionNotAllowed",
      "msg": "mint carries an extension that is not on the allow list"
    }
  ],
  "types": [
    {
      "name": "CapitalFlow",
      "docs": [
        "Direction of the owner's capital movement."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Deposit"
          },
          {
            "name": "Withdraw"
          }
        ]
      }
    },
    {
      "name": "CapitalMoved",
      "docs": [
        "The owner's capital moved (FR-003).",
        "",
        "Formally FR-020 speaks of swaps and quotes, but without this event the P&L",
        "(FR-021) is computed wrongly and **silently**: the collector sees inventory",
        "shrink and has nothing to tell a swap loss from a withdrawal. The figure on the",
        "console looks plausible all the while — which is exactly why the event is here",
        "and not in a later task.",
        "",
        "The other treasury is not mentioned in the event because `deposit` / `withdraw`",
        "move exactly one side; `side` says which."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "vault",
            "type": "pubkey"
          },
          {
            "name": "slot",
            "type": "u64"
          },
          {
            "name": "flow",
            "type": {
              "defined": {
                "name": "CapitalFlow"
              }
            }
          },
          {
            "name": "side",
            "type": {
              "defined": {
                "name": "TreasurySide"
              }
            }
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "treasury_amount_after",
            "docs": [
              "Balance of **this** treasury after the transfer."
            ],
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "InitializeVaultArgs",
      "docs": [
        "Deployment parameters.",
        "",
        "The risk limits are set here rather than by a separate `set_risk_limits` call",
        "(T015): SC-001 gives five commands for the whole path from an empty directory",
        "to the first swap, and a vault that has no limit yet after deployment is an",
        "extra command and a window in which the state exists but the constraint does not."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "pricing_authority",
            "docs": [
              "The right to post quotes (FR-010) — the engine key, hot."
            ],
            "type": "pubkey"
          },
          {
            "name": "halt_authority",
            "docs": [
              "The right to halt in an emergency (FR-024, FR-023c) — separate from capital."
            ],
            "type": "pubkey"
          },
          {
            "name": "max_quote_age_slots",
            "docs": [
              "Quote freshness limit in slots (FR-007)."
            ],
            "type": "u32"
          },
          {
            "name": "max_skew_bps",
            "docs": [
              "Hard bound on inventory skew in basis points (FR-026)."
            ],
            "type": "u16"
          }
        ]
      }
    },
    {
      "name": "QuoteClearReason",
      "docs": [
        "Why the quote disappeared.",
        "",
        "It is cleared from three places, and they are not equal for the console: an",
        "explicit clear is normal engine operation when the feed is silent (FR-014), while",
        "the other two follow an owner action after which the engine will not restore the",
        "price on its own until it sees the new state. Without this field all three would look alike."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Explicit"
          },
          {
            "name": "CapitalWithdrawn"
          },
          {
            "name": "PricingAuthorityChanged"
          }
        ]
      }
    },
    {
      "name": "QuoteCleared",
      "docs": [
        "The quote was cleared (FR-014, FR-020).",
        "",
        "Written **only** when there really was a quote: all three clearing sites call",
        "[`crate::state::Vault::clear_quote`] unconditionally, and without this condition",
        "the history would gain clearings of a price that never existed."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "vault",
            "type": "pubkey"
          },
          {
            "name": "slot",
            "type": "u64"
          },
          {
            "name": "reason",
            "type": {
              "defined": {
                "name": "QuoteClearReason"
              }
            }
          }
        ]
      }
    },
    {
      "name": "QuoteUpdate",
      "docs": [
        "Quote parameters (FR-006). There is no \"per side\" price here — both are",
        "derived from these numbers deterministically (FR-006a)."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "mid_e9",
            "docs": [
              "Market mid in fixed point `1e9`, in **raw units** of quote per raw unit",
              "of base. Converting a human price is the engine's job; the program does",
              "not read the mints' decimals."
            ],
            "type": "u128"
          },
          {
            "name": "spread_bps",
            "docs": [
              "Half of the spread in basis points."
            ],
            "type": "u16"
          },
          {
            "name": "skew_bps",
            "docs": [
              "Mid shift by inventory skew (FR-013)."
            ],
            "type": "i16"
          },
          {
            "name": "max_size_base",
            "docs": [
              "Maximum order size in the base asset (FR-008). It belongs to the quote,",
              "not to the risk limits: the size is declared by whoever declares the price."
            ],
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "QuoteUpdated",
      "docs": [
        "A quote was posted (FR-006, FR-020).",
        "",
        "`slot` here is the same slot that was written to `Vault::quote_slot`, i.e.",
        "the start of the quote's age (FR-007).",
        "",
        "The two side prices are not in the event: bid and ask derive deterministically",
        "from `mid_e9`, `spread_bps` and `skew_bps` via `propamm_quote::side_price_e9` —",
        "the same crate computes them for the program, the adapter and the console.",
        "Writing them into the event would create a fourth source of the same numbers,",
        "and divergence of sources is exactly what SC-006 forbids."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "vault",
            "type": "pubkey"
          },
          {
            "name": "slot",
            "type": "u64"
          },
          {
            "name": "mid_e9",
            "type": "u128"
          },
          {
            "name": "spread_bps",
            "type": "u16"
          },
          {
            "name": "skew_bps",
            "type": "i16"
          },
          {
            "name": "max_size_base",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "RiskLimits",
      "docs": [
        "The owner's risk limits — what the engine cannot change.",
        "",
        "`max_size_base` is **not** here: under FR-006 and FR-008 the maximum size is",
        "carried by the quote, so it is written by `pricing_authority` in `update_quote` (T016).",
        "A size ceiling from the owner would save nothing: a key that can post any",
        "price is not restrained by a size limit — it is restrained by `max_skew_bps`,",
        "and that is right here.",
        "",
        "This is the only place the limits are validated.",
        "",
        "The same type is used by `initialize_vault`: if the checks lived separately,",
        "`set_risk_limits` would let through what deployment refused, and a risk",
        "limit would depend on which road it was set by."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "max_quote_age_slots",
            "docs": [
              "Quote freshness limit in slots (FR-007)."
            ],
            "type": "u32"
          },
          {
            "name": "max_skew_bps",
            "docs": [
              "Hard bound on inventory skew in basis points (FR-026)."
            ],
            "type": "u16"
          }
        ]
      }
    },
    {
      "name": "SwapArgs",
      "docs": [
        "A swap order."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "side",
            "type": {
              "defined": {
                "name": "SwapSide"
              }
            }
          },
          {
            "name": "amount_in",
            "docs": [
              "Amount in, in raw units of the asset the trader gives."
            ],
            "type": "u64"
          },
          {
            "name": "min_amount_out",
            "docs": [
              "Bound on the acceptable result (FR-009). Zero means \"any\", and that is the",
              "trader's deliberate choice, not a missing field."
            ],
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "SwapSide",
      "docs": [
        "Swap direction, named from the **trader's** side.",
        "",
        "Its own type rather than `propamm_quote::Side`: in the crate it knows neither",
        "Borsh nor the IDL, and pulling an Anchor dependency into pure math for one enum",
        "is exactly the trade that would make it unshareable across three consumers."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "BaseToQuote"
          },
          {
            "name": "QuoteToBase"
          }
        ]
      }
    },
    {
      "name": "Swapped",
      "docs": [
        "A swap was executed (FR-020).",
        "",
        "`slot` is when the swap happened, `quote_slot` is when the quote it was priced",
        "by was posted. The difference between them is the quote's age at execution",
        "time: what FR-007 is measured by after the fact, not by intent."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "vault",
            "type": "pubkey"
          },
          {
            "name": "slot",
            "type": "u64"
          },
          {
            "name": "side",
            "docs": [
              "Direction as named from the trader's side — the same type as in the `swap`",
              "arguments, not a copy of it: two copies would diverge in variant order, and",
              "Borsh writes a variant as its index, so a flipped direction in the accounting",
              "would not look like an error."
            ],
            "type": {
              "defined": {
                "name": "SwapSide"
              }
            }
          },
          {
            "name": "amount_in",
            "type": "u64"
          },
          {
            "name": "amount_out",
            "type": "u64"
          },
          {
            "name": "price_e9",
            "docs": [
              "The side price the swap was computed at, in the scale of",
              "[`propamm_quote::PRICE_SCALE`]."
            ],
            "type": "u128"
          },
          {
            "name": "quote_slot",
            "docs": [
              "Slot of the quote the swap was executed against."
            ],
            "type": "u64"
          },
          {
            "name": "base_amount_after",
            "type": "u64"
          },
          {
            "name": "quote_amount_after",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "TreasurySide",
      "docs": [
        "Side of the treasury, derived from the mint passed in.",
        "",
        "Serializable because it goes into the event [`crate::events::CapitalMoved`]:",
        "there it says which side of the inventory changed, and does so in one byte",
        "instead of a thirty-two-byte mint."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Base"
          },
          {
            "name": "Quote"
          }
        ]
      }
    },
    {
      "name": "Vault",
      "docs": [
        "Vault: the owner's capital, authorities, current quote and risk limits.",
        "",
        "Layout (without the 8-byte discriminator):",
        "",
        "| Field | Bytes | Offset |",
        "|---|---|---|",
        "| `owner`, `pricing_authority`, `halt_authority` | 3 × 32 | 0 |",
        "| `base_mint`, `quote_mint` | 2 × 32 | 96 |",
        "| `base_vault`, `quote_vault` | 2 × 32 | 160 |",
        "| `mid_e9` | 16 | 224 |",
        "| `max_size_base`, `quote_slot` | 2 × 8 | 240 |",
        "| `max_quote_age_slots` | 4 | 256 |",
        "| `spread_bps`, `skew_bps`, `max_skew_bps` | 3 × 2 | 260 |",
        "| `halted`, `bump` | 2 × 1 | 266 |",
        "",
        "Fields go from wide to narrow. Borsh writes them packed and knows nothing about",
        "alignment, so the order here is not about memory — it is about readable offsets",
        "in an account dump when a swap does not behave as expected."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "docs": [
              "The sole holder of the capital (FR-002, FR-003). There are no shares; an",
              "outside deposit is refused."
            ],
            "type": "pubkey"
          },
          {
            "name": "pricing_authority",
            "docs": [
              "The right to post quotes (FR-010). Changed by the owner without moving",
              "funds — the engine key is hot, the capital key is not."
            ],
            "type": "pubkey"
          },
          {
            "name": "halt_authority",
            "docs": [
              "The right to halt in an emergency (FR-024, FR-023c). Separate on purpose:",
              "halting may be done by someone not trusted with the capital."
            ],
            "type": "pubkey"
          },
          {
            "name": "base_mint",
            "docs": [
              "Base asset of the pair; fixed at deployment (FR-004)."
            ],
            "type": "pubkey"
          },
          {
            "name": "quote_mint",
            "docs": [
              "Quote asset of the pair; fixed at deployment (FR-004)."
            ],
            "type": "pubkey"
          },
          {
            "name": "base_vault",
            "docs": [
              "Token account of the base asset owned by this PDA."
            ],
            "type": "pubkey"
          },
          {
            "name": "quote_vault",
            "docs": [
              "Token account of the quote asset owned by this PDA."
            ],
            "type": "pubkey"
          },
          {
            "name": "mid_e9",
            "docs": [
              "Market mid in fixed point [`propamm_quote::PRICE_SCALE`], in **raw units**",
              "of quote per raw unit of base. The program does not read the mints'",
              "decimals — that would cost two extra accounts in the SC-002 budget.",
              "Zero means \"no quote posted\", not a price of zero."
            ],
            "type": "u128"
          },
          {
            "name": "max_size_base",
            "docs": [
              "Maximum order size in the base asset (FR-008)."
            ],
            "type": "u64"
          },
          {
            "name": "quote_slot",
            "docs": [
              "Slot in which the quote was posted — the source of its age (FR-007)."
            ],
            "type": "u64"
          },
          {
            "name": "max_quote_age_slots",
            "docs": [
              "Quote freshness limit in slots (FR-007)."
            ],
            "type": "u32"
          },
          {
            "name": "spread_bps",
            "docs": [
              "Half of the spread in basis points."
            ],
            "type": "u16"
          },
          {
            "name": "skew_bps",
            "docs": [
              "Mid shift by inventory skew (FR-013); computed by the engine."
            ],
            "type": "i16"
          },
          {
            "name": "max_skew_bps",
            "docs": [
              "Hard bound on inventory skew in basis points (FR-026)."
            ],
            "type": "u16"
          },
          {
            "name": "halted",
            "docs": [
              "Emergency halt (FR-024). The one flag the program and the adapter each",
              "read on their own — and therefore the main place they could diverge."
            ],
            "type": "bool"
          },
          {
            "name": "bump",
            "docs": [
              "Bump PDA."
            ],
            "type": "u8"
          }
        ]
      }
    }
  ]
}
