//! `forge init` — the project scaffold, parameterized by the pair and the owner (FR-001).
//!
//! # What exactly is "deployed" here
//!
//! Not bytecode. There is one `propamm_vault` program on the network, and a vault
//! is a PDA of the **owner** and the pair (`Vault::pda`), so "your own AMM" means
//! your own PDA in the shared program. Because of this `init` puts neither Rust
//! code nor `Anchor.toml` into the directory: the user needs neither Rust, nor
//! Anchor, nor several SOL for bytecode — and that is exactly why SC-001 (15 minutes, ≤ 5 commands) is reachable at all.
//!
//! # What is not in the directory
//!
//! Keys. `init` **reads** the owner key to record its address and creates none:
//! a key generated by a scaffolding tool would sit in the project directory next
//! to the config and sooner or later end up in git.

use std::path::{Path, PathBuf};

use anchor_lang::prelude::Pubkey;
use anyhow::{bail, Context, Result};
use solana_signer::Signer;

use crate::config::{
    Cluster, Network, Owner, Project, ProjectConfig, VaultEntry, CONFIG_FILE, SCHEMA_VERSION,
};

/// README template of the generated project.
///
/// Embedded in the binary rather than read from next to the executable: `forge`
/// ships as a single file, and a scaffold that looked for a `templates/`
/// directory at runtime would work only from the build tree.
const README_TEMPLATE: &str = include_str!("../templates/README.md.tmpl");
const GITIGNORE_TEMPLATE: &str = include_str!("../templates/gitignore.tmpl");

/// Default path to the owner key — the same as in the Solana CLI.
const DEFAULT_KEYPAIR: &str = ".config/solana/id.json";

/// Command arguments after parsing.
#[derive(Clone, Debug)]
pub struct Options {
    /// Project directory. Created if missing.
    pub path: PathBuf,
    /// Project name; defaults to the directory name.
    pub name: Option<String>,
    pub base_mint: Pubkey,
    pub quote_mint: Pubkey,
    /// Owner keypair; defaults to `~/.config/solana/id.json`.
    pub owner_keypair: Option<PathBuf>,
    pub cluster: Cluster,
    /// Selector of the first vault; defaults to one derived from the pair.
    pub vault_name: Option<String>,
    pub max_quote_age_slots: u32,
    pub max_skew_bps: u16,
    /// Overwrite an existing config.
    pub force: bool,
}

/// What the command created.
#[derive(Debug)]
pub struct Created {
    pub dir: PathBuf,
    pub files: Vec<PathBuf>,
    pub config: ProjectConfig,
}

/// Parse `--pair BASE/QUOTE`.
///
/// # Errors
///
/// If the form is wrong or either side is not an address. The message names
/// the **side**: "not an address" without saying which of the two forces the
/// user to check both.
pub fn parse_pair(text: &str) -> Result<(Pubkey, Pubkey)> {
    let (base, quote) = text
        .split_once('/')
        .with_context(|| format!("the pair is written as BASE/QUOTE, got \"{text}\""))?;
    let base = base
        .trim()
        .parse::<Pubkey>()
        .with_context(|| format!("base mint \"{}\" is not an address", base.trim()))?;
    let quote = quote
        .trim()
        .parse::<Pubkey>()
        .with_context(|| format!("quote mint \"{}\" is not an address", quote.trim()))?;
    if base == quote {
        bail!("both sides of the pair are the same mint ({base}); a vault serves exactly two distinct assets (FR-004)");
    }
    Ok((base, quote))
}

/// Run `forge init`.
///
/// # Errors
///
/// If the owner key is missing, the directory cannot be created, or the config
/// already exists and `--force` is not given.
pub fn run(options: &Options) -> Result<Created> {
    let keypair_path = resolve_keypair(options.owner_keypair.clone())?;
    let owner = read_owner(&keypair_path)?;

    std::fs::create_dir_all(&options.path)
        .with_context(|| format!("cannot create directory {}", options.path.display()))?;

    let config_path = options.path.join(CONFIG_FILE);
    if config_path.exists() && !options.force {
        bail!(
            "{} already exists — the directory is already a PropAMM project; overwrite: forge init --force",
            config_path.display()
        );
    }

    let vault = VaultEntry {
        name: options
            .vault_name
            .clone()
            .unwrap_or_else(|| default_vault_name(&options.base_mint, &options.quote_mint)),
        base_mint: options.base_mint.into(),
        quote_mint: options.quote_mint.into(),
        // Both authorities start in the same hands as the capital. The engine (US2)
        // receives `pricing_authority` by a separate command — that way the right to
        // set the price can be handed over without handing over the right to move money.
        pricing_authority: owner.into(),
        halt_authority: owner.into(),
        max_quote_age_slots: options.max_quote_age_slots,
        max_skew_bps: options.max_skew_bps,
    };

    let config = ProjectConfig {
        version: SCHEMA_VERSION,
        project: Project {
            name: options
                .name
                .clone()
                .unwrap_or_else(|| default_project_name(&options.path)),
        },
        network: Network {
            cluster: options.cluster,
            rpc_url: options.cluster.default_rpc_url().to_string(),
            program_id: propamm_vault::ID.into(),
        },
        owner: Owner {
            pubkey: owner.into(),
            keypair: keypair_path.display().to_string(),
        },
        vaults: vec![vault],
    };

    let mut files = vec![config.write_to(&options.path)?];
    files.push(write_readme(&options.path, &config)?);
    files.push(write_gitignore(&options.path)?);

    Ok(Created {
        dir: options.path.clone(),
        files,
        config,
    })
}

/// Selector of the first vault, derived from the pair.
///
/// The first four characters of each address: exactly as many as a human checks
/// by eye against what the wallet shows, and enough for two vaults in one
/// project not to blur together.
fn default_vault_name(base: &Pubkey, quote: &Pubkey) -> String {
    let head = |key: &Pubkey| key.to_string().chars().take(4).collect::<String>();
    format!("{}-{}", head(base), head(quote))
}

fn default_project_name(path: &Path) -> String {
    path.canonicalize()
        .ok()
        .as_deref()
        .and_then(Path::file_name)
        .or_else(|| path.file_name())
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_else(|| "propamm-project".to_string())
}

fn resolve_keypair(given: Option<PathBuf>) -> Result<PathBuf> {
    if let Some(path) = given {
        return Ok(path);
    }
    let home = dirs::home_dir().context("cannot determine the home directory — pass --owner")?;
    Ok(home.join(DEFAULT_KEYPAIR))
}

/// The owner's address from the keypair file.
///
/// The key is **read**, not generated: the owner's address goes into the vault
/// seeds, so a mistake here means deploying a vault nobody controls.
fn read_owner(path: &Path) -> Result<Pubkey> {
    if !path.exists() {
        bail!(
            "no owner keypair at {} — create one: solana-keygen new, or name your own: forge init --owner <path>",
            path.display()
        );
    }
    let keypair = solana_keypair::read_keypair_file(path)
        .map_err(|err| anyhow::anyhow!("{} is not a Solana keypair: {err}", path.display()))?;
    // Crossing between solana crate generations: `Signer::pubkey` returns a key from
    // the same triple anchor-lang lives on, so the bytes are taken directly.
    Ok(Pubkey::new_from_array(keypair.pubkey().to_bytes()))
}

fn write_readme(dir: &Path, config: &ProjectConfig) -> Result<PathBuf> {
    let vault = config
        .vaults
        .first()
        .expect("init always creates one vault");
    let text = fill(
        README_TEMPLATE,
        &[
            ("project", &config.project.name),
            ("cluster", &config.network.cluster.to_string()),
            ("rpc_url", &config.network.rpc_url),
            ("program_id", &config.network.program_id.to_string()),
            ("owner", &config.owner.pubkey.to_string()),
            ("vault", &vault.name),
            ("base_mint", &vault.base_mint.to_string()),
            ("quote_mint", &vault.quote_mint.to_string()),
            (
                "max_quote_age_slots",
                &vault.max_quote_age_slots.to_string(),
            ),
            ("max_skew_bps", &vault.max_skew_bps.to_string()),
        ],
    )?;
    let path = dir.join("README.md");
    std::fs::write(&path, text).with_context(|| format!("cannot write {}", path.display()))?;
    Ok(path)
}

fn write_gitignore(dir: &Path) -> Result<PathBuf> {
    let path = dir.join(".gitignore");
    std::fs::write(&path, GITIGNORE_TEMPLATE)
        .with_context(|| format!("cannot write {}", path.display()))?;
    Ok(path)
}

/// Substitute the values into the template and **make sure no placeholder is left**.
///
/// The second half is the main one here. An unreplaced `{{owner}}` is not a
/// broken file, it is a file that looks right and silently lies about the
/// address; it would be noticed when someone sent funds to the wrong place. So
/// a template with a leftover turns `init` into an error, not a warning.
///
/// # Errors
///
/// If `{{` remains after substitution.
fn fill(template: &str, values: &[(&str, &String)]) -> Result<String> {
    let mut text = template.to_string();
    for (key, value) in values {
        text = text.replace(&format!("{{{{{key}}}}}"), value);
    }
    if let Some(at) = text.find("{{") {
        let tail: String = text[at..].chars().take(40).collect();
        bail!("an unfilled placeholder remains in the template: {tail}");
    }
    Ok(text)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(tag: u8) -> Pubkey {
        Pubkey::new_from_array([tag; 32])
    }

    #[test]
    fn a_pair_is_two_addresses_separated_by_a_slash() {
        let base = key(1);
        let quote = key(2);
        let parsed = parse_pair(&format!("{base}/{quote}")).expect("the pair did not parse");
        assert_eq!(parsed, (base, quote));
    }

    #[test]
    fn a_broken_side_of_the_pair_is_named_in_the_message() {
        let quote = key(2);
        let err = parse_pair(&format!("not-a-key/{quote}")).unwrap_err();
        assert!(
            format!("{err}").contains("base"),
            "the message does not name the side: {err}"
        );

        let base = key(1);
        let err = parse_pair(&format!("{base}/not-a-key")).unwrap_err();
        assert!(
            format!("{err}").contains("quote"),
            "the message does not name the side: {err}"
        );
    }

    #[test]
    fn a_degenerate_pair_is_refused_before_anything_is_written() {
        let same = key(7);
        let err = parse_pair(&format!("{same}/{same}")).unwrap_err();
        assert!(format!("{err}").contains("the same mint"), "{err}");
    }

    #[test]
    fn the_default_vault_name_shows_both_sides() {
        let name = default_vault_name(&key(1), &key(2));
        let (base, quote) = (key(1).to_string(), key(2).to_string());
        assert_eq!(name, format!("{}-{}", &base[..4], &quote[..4]));
    }

    /// The guard in [`fill`] must really fire — otherwise it would remain a line
    /// of code nobody ever executed.
    #[test]
    fn a_template_with_a_leftover_placeholder_is_an_error() {
        let value = "value".to_string();
        let err = fill("{{known}} and {{forgotten}}", &[("known", &value)]).unwrap_err();
        assert!(format!("{err}").contains("forgotten"), "{err}");
    }
}
