#!/usr/bin/env node
// IDL vendoring: `target/idl/propamm_vault.json` → `packages/sdk/src/idl.ts`.
//
// The copy is not for convenience. `target/` is under `.gitignore`, i.e. a fresh
// clone arrives with no IDL at all, and `anchor build` is available only in WSL.
// An SDK that read `target/` would build neither in CI nor on a machine without
// the Solana toolchain. So a copy lives in the repository, and this script is
// the only way to update it.
//
// The copy is exactly a copy, not a rework: field names stay in snake_case, as
// Anchor writes them. The renaming to camelCase lives in the layout tables
// (`src/codecs.ts`), where both names sit side by side in one row — otherwise
// the IssuerForge story repeats, where the IDL type and the runtime value
// diverged by case and the compiler did not see it.
//
//   node scripts/sync-idl.mjs           update the copy
//   node scripts/sync-idl.mjs --check   fail if the copy is stale (for the gate)

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const source = join(root, 'target', 'idl', 'propamm_vault.json')
const target = join(root, 'packages', 'sdk', 'src', 'idl.ts')

const header = `// GENERATED by \`node scripts/sync-idl.mjs\` from target/idl/propamm_vault.json.
// Do not edit by hand: the next sync overwrites it. The source of truth is the Rust program.
//
// Field names here are in snake_case — the way Anchor writes them. The crossing to
// camelCase happens in exactly one place, the layout tables in \`src/codecs.ts\`.

import type { PropammVaultIdl } from './idl-schema.js'

export const PROPAMM_VAULT_IDL: PropammVaultIdl = `

const BUILD_HINT = 'scripts/wsl-build.sh build (in WSL — see the header of the script itself)'
const check = process.argv.includes('--check')

function render() {
  let idl
  try {
    idl = readFileSync(source, 'utf8')
  } catch {
    // In --check mode a missing `target/` is not an error but the state of a fresh
    // clone: the IDL is built only where the Solana toolchain is. Making the gate red
    // on a machine where the program was simply not built would teach people to ignore it.
    if (check) {
      console.log(`IDL: ${source} missing — nothing to compare, step skipped (${BUILD_HINT})`)
      process.exit(0)
    }
    console.error(`No ${source}.\nThe IDL is built in WSL: ${BUILD_HINT}`)
    process.exit(2)
  }
  // Re-read through JSON.parse so the canonical form lands in the file: sync twice
  // in a row has to yield the same bytes, otherwise --check would be noisy on formatting.
  const body = JSON.stringify(JSON.parse(idl), null, 2)
  return `${header}${body}\n`
}

const rendered = render()

if (check) {
  let current = ''
  try {
    current = readFileSync(target, 'utf8')
  } catch {
    console.error(`No ${target} — run: node scripts/sync-idl.mjs`)
    process.exit(1)
  }
  if (current !== rendered) {
    console.error(
      'The vendored IDL is stale relative to target/idl/propamm_vault.json.\nUpdate: node scripts/sync-idl.mjs',
    )
    process.exit(1)
  }
  console.log('IDL: the copy matches target/idl/propamm_vault.json')
} else {
  // Explicitly LF: on Windows any CRLF here would make --check red forever.
  writeFileSync(target, rendered, { encoding: 'utf8' })
  console.log(`IDL → ${target}`)
}
